# Jekyll configuration for Open SDG platform

# Tell the Remote Theme plugin to use the Open SDG platform (Jekyll theme).
remote_theme: open-sdg/open-sdg@2.3.2
destination: public

# Site settings
title: U.K. Indicators For The Sustainable Development Goals

# ⚠️ Remove or comment out this line to avoid conflict
# url: ""

environment: staging

# Pages
collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true
    permalink: /updates/:year/:month/:day/:title.html
  indicators:
    output: true
  goals:
    output: true

plugins:
  - jekyll-remote-theme
  - jekyll-open-sdg-plugins
  - jekyll-toc

# Exclude some files/folders.
exclude:
  - vendor
  - scripts
  - remotedata
  - Gemfile
  - Gemfile.lock
  - README
  - README.md
  - LICENSE

country:
  name: UK
  adjective: UK

# ✅ Correct GitHub Pages config:
url: "https://greenorbitspace.github.io"
baseurl: "/sdg-indicators"

kramdown:
  input: Kramdown