# Jekyll configuration for Open SDG platform

remote_theme: open-sdg/open-sdg@2.3.2
destination: public

# UK-specific config settings
survey_url: https://www.smartsurvey.co.uk/s/EZZRYJ/
hotjar: false

# Site settings
title: U.K. Indicators For The Sustainable Development Goals

# Set your environment
environment: production    # Change from staging to production if live

# Collections
collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true
    permalink: /updates/:year/:month/:day/:title.html
  indicators:
    output: true
  goals:
    output: true

plugins:
  - jekyll-remote-theme
  - jekyll-open-sdg-plugins
  - jekyll-toc

exclude:
  - vendor
  - scripts
  - remotedata
  - Gemfile
  - Gemfile.lock
  - README
  - README.md
  - LICENSE

country:
  name: UK
  adjective: UK

# === UPDATED ===
url: "https://sdgs.greenorbit.space"   # Your root production URL
baseurl: ""                             # Empty string because deployed at root

kramdown:
  input: Kramdown