name: Deploy Open SDG site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-open-sdg
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
          bundler-cache: true    # caches gems between runs

      - name: Install dependencies
        run: bundle config set deployment 'true' && bundle install --jobs 4 --retry 3

      - name: Build Jekyll site
        run: bundle exec jekyll build -d public

      - name: Add CNAME file
        run: echo "sdgs.greenorbit.space" > public/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
          publish_branch: gh-pages
          keep_files: false
          commit_message: "Deploy Open SDG site - ${{ github.sha }}"